### ISSUE TITLE
Sequence Handler

### ISSUE THREAD

**Issue by fraVerryns** [UnquietCode/JState#17]
Hello, I am using your library for a project. I have a question about onSequence. It seems like the list should have the same size. If for example I have two lists: one of size 3 and the other of size 4, the callbacks is always called after 4 States. So the callback for the list of size 3 is called but with a delay of one State. Is there a way to deal with that?
Thank you
Francesco

**Comment by UnquietCode** [comment]
Thanks for the bug report. I was able to track down the problem.
