### ISSUE TITLE
Support Async Transitions

### ISSUE THREAD

**Issue by UnquietCode** [UnquietCode/JState#2]
Something like, always add a callback to a queue,
so default is async, but if hits from the non-async
method then immediately pull the CB off the queue and execute it.

Or, returns a callback and can either execute it or queue it.

Either way, larger effort will be in the transition method to detect
that there is outstanding work and defer the transition (if not async)
or queue it (if async).

**Comment by bentwire** [comment]
What would it take to get this working?  I am trying to transition my SM from a [CountdownTimer](https://developer.android.com/reference/android/os/CountDownTimer.html) and it is failing. :)

Thanks,
Mike

**Comment by UnquietCode** [comment]
Hi there. I actually don't think this would take much effort, I'm just fairly busy these days, so maybe I can take a look this weekend. Could you describe the failure you are seeing? It looks like the `CountDownTimer` only issues an `onTick(...)` call one at a time, so it's not immediately clear why you would need an asynchronous transition unless you're competing with other threads trying to transition the state machine.

**Comment by bentwire** [comment]
Yes, I was calling a state transition from an event fired from another thread.  I ended up using a Handler to do all the transitions, but not 100% ideal.

What changes do you think would need to be made to the library?

**Comment by UnquietCode** [comment]
I think the general approach would be to put an `Executor` inside of the base state machine class, with the default being the SingleThreadedExecutor which has a queue size of 1 and runs all tasks blocking in the current thread. Then a private constructor could be added to accept a different `Executor` instance, one which has an unlimited queue size but only a single runner. That way the order of transitions is preserved, even when they are being run async.

The part that I am unsure about is error handling. If an asynchronous transition fails, presumably all of the queued transitions should also fail. I'd like to take a look at this later in the week to see what's possible, but that's my two cents right now.

**Comment by UnquietCode** [comment]
@bentwire Do you have any thoughts on how failures should be handled? Right now if a failure occurs all future async transitions are cancelled and the error is thrown.

**Comment by bentwire** [comment]
That is basically how I have been doing it.  Also illegal state transitions could cause the queue to fail (or be ignored?), not 100% sure if that is ideal or not but that is how I have been handling it as well (I ignore the illegal transition but log it at the moment).
