### ISSUE TITLE
Add OSGi manifest headers

### ISSUE THREAD

**Issue by mattbishop** [UnquietCode/JState#7]
I'd like to use JState in an osgi project but it needs to have it's manifest set up to declare the packages it provides.

**Comment by UnquietCode** [comment]
This seems useful, but I don't use it myself or know enough about it. What effect does changing the packaging type have on the rest of the build?

**Comment by mattbishop** [comment]
'bundle' just triggers the bundle plugin to generate the correct manifest headers. The alternative way is to muck about with the jar plugin and hand-roll the manifest headers.

In the end the output is a jar file, but 'bundle' version has extra headers in the manifest that only apply to an OSGi container.

**Comment by UnquietCode** [comment]
@mattbishop I'm having an issue with the felix plugin where its causing all of the build artifacts to be signed twice and creating invalid signatures. Any idea how one might resolve this?

**Comment by UnquietCode** [comment]
Nevermind, seems to be fixed in the latest version of the plugin. The latest 2.1 release is currently being synced to the sonatype central repository and includes the OSGI changes. Thanks for your patience.

**Comment by mattbishop** [comment]
Thanks!
